module Funes
  # Raised when a projection configured with `persists_per_change` points at a
  # materialization model whose table is missing the required `version` column.
  #
  # Per-change projections persist one row per version of the projection's state,
  # keyed by `(idx, version)`. This requires a materialization table generated by
  # {Funes::Generators::PerChangeMaterializationTableGenerator} (or an equivalent
  # schema). If `persists_per_change` is declared but the backing table lacks the
  # `version` column, Funes raises this error on the first persistence attempt.
  #
  # @example Incorrectly configured per-change projection
  #   class BalanceHistoryProjection < Funes::Projection
  #     materialization_model BalanceSnapshot # table has only `idx`, no `version`
  #     persists_per_change
  #   end
  #
  #   # Raises Funes::InvalidPerChangeMaterializationTable on materialize!
  #   BalanceHistoryProjection.materialize!(events, "account-1")
  #
  # @example Correctly configured per-change projection
  #   # Generate the table first:
  #   #   bin/rails generate funes:per_change_materialization_table BalanceHistory balance:decimal
  #   class BalanceHistoryProjection < Funes::Projection
  #     materialization_model BalanceHistory
  #     persists_per_change
  #   end
  class InvalidPerChangeMaterializationTable < StandardError; end
end
